### ISSUE TITLE
Viikko 7 deadline pvm

### ISSUE THREAD

**Issue by t0ffe** [ohjelmistotuotanto-hy/ohjelmistotuotanto-hy.github.io#287]
https://github.com/ohjelmistotuotanto-hy/ohjelmistotuotanto-hy.github.io/blob/97684d944906f55a843a19cf8181f413b255d02d/_config.yml#L35

20.12.**2024** ei ole keskiviikko.
Viime vuonna 20.12.**2023** oli keskiviikko.
Onko 2024 DL 20.12. perjantai, 18.12. keskiviikko vai jokin muu?

**Comment by mluukkai** [comment]
pidetään 20.12. ennallaan ja muutetaan ke -> pe
